spring:
  cloud:
    gateway:
      routes:
        - id: test
          uri: https://www.qq.com
          predicates:
            - Query=url,qq
#        精确路由放在高优先级
        - id: gulimall_product
          uri: lb://gulimall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: third_party_route
          uri: lb://gulimall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}

        - id: gulimall_member
          uri: lb://gulimall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: gulimall_ware
          uri: lb://gulimall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
#          断言匹配
            - Path=/api/**
          filters:
#          路径重写
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}

