spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      oss:
        access-key: LTAI5tAnbpkujmuy66RXcGZTssecret-key
        secret-key: qojtxf0LV1K04DEY4yvuN2Wz1egqTS
        endpoint: oss-cn-guangzhou.aliyuncs.com
        bucket: overwatchguli

  application:
    name: gulimall-third-party



server:
  port: 30000

